- name: My first play
  hosts: testmachine
  gather_facts: false
  tasks:
    - name: Another way to call known_hosts
      ansible.builtin.known_hosts:
        name: {{ inventory_hostname }}
        key: 51.20.114.23 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFlMCrhfL9gVMCWxMKn+5tKbWBlL0YfXIX/lfLcoLa7W
        path: /etc/ssh/ssh_known_hosts
        state: present
    - name: Delayed gathering of facts
      setup:
    - name: Ping my hosts
      ansible.builtin.ping:

